
const Data = {

"CharacterData" : {
    'Baby Peach':{'Speed':2.5,'MiniTurbo':4.5},
    'Baby Daisy':{'Speed':2.5,'MiniTurbo':4.5}, 
    'Baby Rosalina':{'Speed':2.5,'MiniTurbo':4.5}, 
    'Lemmy':{'Speed':2.5,'MiniTurbo':4.5}, 
    'Baby Mario':{'Speed':2.75,'MiniTurbo':4.5}, 
    'Baby Luigi':{'Speed':2.75,'MiniTurbo':4.5}, 
    'Dry Bones':{'Speed':2.75,'MiniTurbo':4.5}, 
    'Light Mii':{'Speed':2.75,'MiniTurbo':4.5}, 
    'Toadette':{'Speed':3,'MiniTurbo':4.25}, 
    'Wendy':{'Speed':3,'MiniTurbo':4.25}, 
    'Isabelle':{'Speed':3,'MiniTurbo':4.25}, 
    'Koopa Troopa':{'Speed':3,'MiniTurbo':4.25}, 
    'Lakitu':{'Speed':3,'MiniTurbo':4.25}, 
    'Bowser Jr.':{'Speed':3,'MiniTurbo':4.25}, 
    'Toad':{'Speed':3.25,'MiniTurbo':4.25}, 
    'Shy Guy':{'Speed':3.25,'MiniTurbo':4.25}, 
    'Larry':{'Speed':3.25,'MiniTurbo':4.25}, 
    'Cat Peach':{'Speed':3.5,'MiniTurbo':4}, 
    'Inkling Girl':{'Speed':3.5,'MiniTurbo':4}, 
    'Female Villager':{'Speed':3.5,'MiniTurbo':4}, 
    'Peach':{'Speed':3.75,'MiniTurbo':4.25}, 
    'Daisy':{'Speed':3.75,'MiniTurbo':4.25}, 
    'Yoshi':{'Speed':3.75,'MiniTurbo':4.25}, 
    'Birdo':{'Speed':3.75,'MiniTurbo':4.25}, 
    'Tanooki Mario':{'Speed':3.75,'MiniTurbo':4}, 
    'Inkling Boy':{'Speed':3.75,'MiniTurbo':4}, 
    'Male Villager':{'Speed':3.75,'MiniTurbo':4}, 
    'Mario':{'Speed':4,'MiniTurbo':4}, 
    'Ludwig':{'Speed':4,'MiniTurbo':4}, 
    'Medium Mii':{'Speed':4,'MiniTurbo':4}, 
    'Luigi':{'Speed':4,'MiniTurbo':4}, 
    'Iggy':{'Speed':4,'MiniTurbo':4}, 
    'Rosalina':{'Speed':4.25,'MiniTurbo':3.75}, 
    'King Boo':{'Speed':4.25,'MiniTurbo':3.75}, 
    'Link':{'Speed':4.25,'MiniTurbo':3.75}, 
    'Metal Mario':{'Speed':4.25,'MiniTurbo':3.5}, 
    'Gold Mario':{'Speed':4.25,'MiniTurbo':3.5}, 
    'Pink Gold Peach':{'Speed':4.25,'MiniTurbo':3.5}, 
    'Waluigi':{'Speed':4.5,'MiniTurbo':3.5}, 
    'Donkey Kong':{'Speed':4.5,'MiniTurbo':3.5}, 
    'Roy':{'Speed':4.5,'MiniTurbo':3.5}, 
    'Wario':{'Speed':4.75,'MiniTurbo':3.25}, 
    'Dry Bowser':{'Speed':4.75,'MiniTurbo':3.25}, 
    'Bowser':{'Speed':4.75,'MiniTurbo':3.25}, 
    'Morton':{'Speed':4.75,'MiniTurbo':3.25}, 
    'Heavy Mii':{'Speed':4.75,'MiniTurbo':3.25}
    },
"KartData" : {
    'Standard Kart':{'Speed':0,'MiniTurbo':0}, 
    'The Duke':{'Speed':0,'MiniTurbo':0}, 
    '300 SL Roadster':{'Speed':0,'MiniTurbo':0}, 
    'Pipe Frame':{'Speed':-.5,'MiniTurbo':.25}, 
    'Varmint':{'Speed':-.5,'MiniTurbo':.25}, 
    'City Tripper':{'Speed':-.5,'MiniTurbo':.25}, 
    'Mach 8':{'Speed':0,'MiniTurbo':0}, 
    'Sports Coupe':{'Speed':0,'MiniTurbo':0}, 
    'Inkstriker':{'Speed':0,'MiniTurbo':0}, 
    'Steel Driver':{'Speed':.25,'MiniTurbo':-.5}, 
    'Tri-Speeder':{'Speed':.25,'MiniTurbo':-.5}, 
    'Bone Rattler':{'Speed':.25,'MiniTurbo':-.5}, 
    'Cat Cruiser':{'Speed':-.25,'MiniTurbo':.25}, 
    'Teddy Buggy':{'Speed':-.25,'MiniTurbo':.25}, 
    'Comet':{'Speed':-.25,'MiniTurbo':.25}, 
    'Yoshi Bike':{'Speed':-.25,'MiniTurbo':.25}, 
    'Circuit Special':{'Speed':.5,'MiniTurbo':-.75}, 
    'B-Dasher':{'Speed':.5,'MiniTurbo':-.75}, 
    'P-Wing':{'Speed':.5,'MiniTurbo':-.75}, 
    'Badwagon':{'Speed':.5,'MiniTurbo':-1}, 
    'GLA':{'Speed':.5,'MiniTurbo':-1}, 
    'Standard ATV':{'Speed':.5,'MiniTurbo':-1}, 
    'Prancer':{'Speed':.25,'MiniTurbo':-.25}, 
    'Sport Bike':{'Speed':.25,'MiniTurbo':-.25}, 
    'Jet Bike':{'Speed':.25,'MiniTurbo':-.25},
    'Biddybuggy':{'Speed':-.75,'MiniTurbo':.5}, 
    'Mr Scooty':{'Speed':-.75,'MiniTurbo':.5}, 
    'Landship':{'Speed':-.5,'MiniTurbo':.25}, 
    'Streetle':{'Speed':-.5,'MiniTurbo':.25}, 
    'Sneaker':{'Speed':.25,'MiniTurbo':-.25}, 
    'Gold Standard':{'Speed':.25,'MiniTurbo':-.25}, 
    'Master Cycle':{'Speed':.25,'MiniTurbo':-.25}, 
    'W 25 Silver Arrow':{'Speed':-.25,'MiniTurbo':0}, 
    'Standard Bike':{'Speed':-.25,'MiniTurbo':0}, 
    'Flame Rider':{'Speed':-.25,'MiniTurbo':0}, 
    'Wild Wiggler':{'Speed':-.25,'MiniTurbo':0}, 
    'Blue Falcon':{'Speed':.25,'MiniTurbo':-.25}, 
    'Splat Buggy':{'Speed':.25,'MiniTurbo':-.25}, 
    'Tanooki Kart':{'Speed':-.25,'MiniTurbo':-.25}, 
    'Koopa Clown':{'Speed':-.25,'MiniTurbo':-.25}, 
    'Master Cycle Zero':{'Speed':-.25,'MiniTurbo':-.25}
    },
"WheelData" : {
    'Standard':{'Speed':0,'MiniTurbo':0}, 
    'Blue Standard':{'Speed':0,'MiniTurbo':0}, 
    'GLA Tires':{'Speed':0,'MiniTurbo':0}, 
    'Monster':{'Speed':0,'MiniTurbo':-.25}, 
    'Hot Monster':{'Speed':0,'MiniTurbo':-.25}, 
    'Ancient Tires':{'Speed':0,'MiniTurbo':-.25}, 
    'Roller':{'Speed':-.5,'MiniTurbo':.5}, 
    'Azure Roller':{'Speed':-.5,'MiniTurbo':.5}, 
    'Slim':{'Speed':.25,'MiniTurbo':-.25}, 
    'Wood':{'Speed':.25,'MiniTurbo':-.75}, 
    'Crimson Slim':{'Speed':.25,'MiniTurbo':-.75}, 
    'Slick':{'Speed':.5,'MiniTurbo':-.75}, 
    'Cyber Slick':{'Speed':.5,'MiniTurbo':-.75}, 
    'Metal':{'Speed':.5,'MiniTurbo':-.75}, 
    'Gold Tires':{'Speed':.5,'MiniTurbo':-.75}, 
    'Button':{'Speed':-.25,'MiniTurbo':.25}, 
    'Leaf Tires':{'Speed':-.25,'MiniTurbo':.25}, 
    'Off-Road':{'Speed':.25,'MiniTurbo':-.5}, 
    'Retro Off-Road':{'Speed':.25,'MiniTurbo':-.5}, 
    'Triforce Tires':{'Speed':.25,'MiniTurbo':-.5}, 
    'Sponge':{'Speed':-.25,'MiniTurbo':.25}, 
    'Cushion':{'Speed':-.25,'MiniTurbo':.25}
    },
"GliderData" : {
    'Super Glider':{'Speed':0,'MiniTurbo':0}, 
    'Waddle Wing':{'Speed':0,'MiniTurbo':0}, 
    'Hylian Kite':{'Speed':0,'MiniTurbo':0}, 
    'Cloud Glider':{'Speed':-.25,'MiniTurbo':.25}, 
    'Parachute':{'Speed':-.25,'MiniTurbo':.25}, 
    'Flower Glider':{'Speed':-.25,'MiniTurbo':.25}, 
    'Paper Glider':{'Speed':-.25,'MiniTurbo':.25}, 
    'Wario Wing':{'Speed':0,'MiniTurbo':0}, 
    'Plane Glider':{'Speed':0,'MiniTurbo':0}, 
    'Gold Glider':{'Speed':0,'MiniTurbo':0}, 
    'Paraglider':{'Speed':0,'MiniTurbo':0}, 
    'Peach Parasol':{'Speed':-.25,'MiniTurbo':.25}, 
    'Parafoil':{'Speed':-.25,'MiniTurbo':.25}, 
    'Bowser Kite':{'Speed':-.25,'MiniTurbo':.25}, 
    'MKTV Parafoil':{'Speed':-.25,'MiniTurbo':.25}
    }
}

export default Data;